### ISSUE TITLE
[QUESTION] Clone from template

### ISSUE THREAD

**Issue by lotherk** [danitso/terraform-provider-proxmox#1]
Thank you for this awesome provider! As far as I can tell it seems to be the best out there yet.

I want to ask if and how it is possible to create a vm out of a template?

I expected proxmox_virtual_environment_vm to have an option to specify a template but there isn't one. I also read the source (my go knowledge is very limited) but can't find anything there either. 

Is it possible and if not, is there a workaround?

Thanks in advance!

**Comment by danitso-dp** [comment]
> Thank you for this awesome provider! As far as I can tell it seems to be the best out there yet.
> 
> I want to ask if and how it is possible to create a vm out of a template?
> 
> I expected proxmox_virtual_environment_vm to have an option to specify a template but there isn't one. I also read the source (my go knowledge is very limited) but can't find anything there either.
> 
> Is it possible and if not, is there a workaround?
> 
> Thanks in advance!

This feature is currently not available but will be added to v0.3.0 later this week (current master branch), which will be released next week.

In case you are missing other features, don't hesitate to open more feature requests.

**Comment by danitso-dp** [comment]
I forgot to mention that in case you have a simple VM with a single disk, you can export that disk in qcow2 format and let the provider use that to build a new VM for you. You can also use a standard cloud image like the one for Ubuntu and set up your server using cloud-init. This is showcased in the example folder.

**Comment by lotherk** [comment]
Hi, thank you for your response!

It doesn't seem to work for me though. 

rancher.tf

**Comment by danitso-dp** [comment]
> Hi, thank you for your response!
> 
> It doesn't seem to work for me though.
> 
> rancher.tf:
> 
> ```
> resource "proxmox_virtual_environment_vm" "rancher" {
>         name = "rancher01"
> 
>         agent {
>                 enabled = true
>         }
> 
>         cpu {
>                 cores = 4
>                 type = "host"
>         }
> 
>         memory {
>                 dedicated = 4096
>         }
> 
>         network_device {
>                 bridge = "vmbr80"
>         }
> 
>         node_name = "pve01"
> 
>         operating_system {                                                                
>                 type = "l26"
>         }                                                                                  "
> 
>         clone {
>                 datastore_id = "nfs"
>                 node_name = "fs02"
>                 vm_id = 102
>         }
> 
>         vm_id = 501
> }
> ```
> 
> it gets created but immediately fails with
> 
> ```
> Error: Received an HTTP 500 response - Reason: Configuration file 'nodes/pve01/qemu-server/501.conf' does not exist
> 
>   on rancher.tf line 1, in resource "proxmox_virtual_environment_vm" "rancher":
>    1: resource "proxmox_virtual_environment_vm" "rancher" {
> ```
> 
> The clone succeeds on proxmox, though. Terraform wants to recreate the vm when running apply and fails again with the above error.

It's most likely due to cloning being an asynchronous operation from one node to another, which the provider is not waiting for right now. This should be fairly simple to fix so I'll take a look at it shortly.

**Comment by danitso-dp** [comment]
I've pushed a new commit which should resolve the issue.

**Comment by lotherk** [comment]
Terraform now crashes, see: [crash.log](https://github.com/danitso/terraform-provider-proxmox/files/4096328/crash.log), [rancher.tf.txt](https://github.com/danitso/terraform-provider-proxmox/files/4096353/rancher.tf.txt)

**Comment by danitso-dp** [comment]
This should now be fixed.

**Comment by lotherk** [comment]
Thank you! We're getting closer, I think. :-)

Now I got
```
proxmox_virtual_environment_vm.rancher: Creating...

Error: Received an HTTP 400 response - Reason: Parameter verification failed. (delete: you can't use '-net0' and -delete net0' at the same time)

  on rancher.tf line 1, in resource "proxmox_virtual_environment_vm" "rancher":
   1: resource "proxmox_virtual_environment_vm" "rancher" {

```

**Comment by danitso-dp** [comment]
Try with the latest commit I just pushed.

**Comment by lotherk** [comment]
It works! Thank you very much!

**Comment by danitso-dp** [comment]
Great to hear and thanks for testing this feature, especially before the release of v0.3.0.

In case you run into other problems, don't hesitate to create a new issue.
