### ISSUE TITLE
[BUG] Terraform apply "Only root can set 'arch' config"

### ISSUE THREAD

**Issue by Crazyscorpio88** [danitso/terraform-provider-proxmox#10]
Hi @danitso-dp,

We are having some problems with Terraform Provider, we are trying to create a VM with it and it returns a "Error: Received an HTTP 500 response - Reason: only root can set 'arch' config"

We made different tests :
- Calling the RestAPI
```
USER=uterra@pve
PASS=password
HOST=10.0.0.11:8006

curl -s -k -d "username=$USER&password=$PASS" \
 https://$HOST/api2/json/access/ticket\
| jq --raw-output '.data.ticket' | sed 's/^/PVEAuthCookie=/' > cookie

curl -s -k -d "username=$USER&password=$PASS" \
 https://$HOST/api2/json/access/ticket\
| jq --raw-output '.data.CSRFPreventionToken' | sed 's/^/CSRFPreventionToken:/' > csrftoken

curl -sk -H "$(<csrftoken)" -b "$(<cookie)" -X DELETE https://$HOST/api2/json/nodes/pve/qemu/789

curl -sk -H "$(<csrftoken)" -b "$(<cookie)" -d vmid=789 https://$HOST/api2/json/nodes/pve/qemu|jq
```
It returns : 

> {"data":null}{
  "data": "UPID:pve:00001BF3:00296B59:5E7E0B69:qmcreate:789:uterra@pve:"
}

But when we do quite the same on the Provider : 

```
provider "proxmox" {
  virtual_environment {
    endpoint = "https://10.0.0.11:8006"
    username = "uterra@pve"
    password = "password"
    insecure = true
  }
}

resource "proxmox_virtual_environment_vm" "pve-test1" {
  name        = "terraform-provider-proxmox-dummy-vm"
  description = "Managed by Terraform Nico"

  node_name = "pve"
  vm_id     = 788
  pool_id = data.proxmox_virtual_environment_pool.local.id
}

data "proxmox_virtual_environment_pool" "local" {
  pool_id = "local"
}
```
When we execute : `terraform plan`
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.proxmox_virtual_environment_pool.local: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.pve-test1 will be created
  + resource "proxmox_virtual_environment_vm" "pve-test1" {
      + acpi                    = true
      + bios                    = "seabios"
      + description             = "Managed by Terraform Nico"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + name                    = "terraform-provider-proxmox-dummy-vm"
      + network_interface_names = (known after apply)
      + node_name               = "pve"
      + pool_id                 = "local"
      + started                 = true
      + tablet_device           = true
      + template                = false
      + vm_id                   = 788
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

```
And when we run : `terraform apply `

```
data.proxmox_virtual_environment_pool.local: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # proxmox_virtual_environment_vm.pve-test1 will be created
  + resource "proxmox_virtual_environment_vm" "pve-test1" {
      + acpi                    = true
      + bios                    = "seabios"
      + description             = "Managed by Terraform Nico"
      + id                      = (known after apply)
      + ipv4_addresses          = (known after apply)
      + ipv6_addresses          = (known after apply)
      + keyboard_layout         = "en-us"
      + mac_addresses           = (known after apply)
      + name                    = "terraform-provider-proxmox-dummy-vm"
      + network_interface_names = (known after apply)
      + node_name               = "pve"
      + pool_id                 = "local"
      + started                 = true
      + tablet_device           = true
      + template                = false
      + vm_id                   = 788
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_vm.pve-test1: Creating...

Error: Received an HTTP 500 response - Reason: only root can set 'arch' config

  on test.tf line 10, in resource "proxmox_virtual_environment_vm" "pve-test1":
  10: resource "proxmox_virtual_environment_vm" "pve-test1" {


```
 Are you aware of an issue with it? We tried with root@pam it worked like a charm.
We applied all the necessary roles to the group and user uterra, nothing changed.

Thanks for your help.

**Comment by danitso-dp** [comment]
It seems that no matter what permissions you grant a PVE account, it won't be permitted to change the CPU architecture of the VM (the `arch` API parameter).

While it would be best if Proxmox VE actually allowed this with the proper permissions, it's probably easier to implement a workaround in the provider for now, which will avoid specifying the `arch` parameter with PVE accounts as long as the CPU architecture is set to the default value. I can probably do a pull request for this later today or tomorrow.

**Comment by danitso-dp** [comment]
@Crazyscorpio88 can you provide me with a list of permissions assigned to the PVE account you're using? That way I can do a test with similar permissions and verify that the upcoming fix works.

**Comment by Crazyscorpio88** [comment]
Arf, it is what i feared.

Yes here they are for PVETerraformGroup : 
`VM.Config.CPU, SDN.Audit, Datastore.AllocateTemplate, VM.Audit, VM.Allocate, VM.Config.Network, Sys.Modify, Datastore.AllocateSpace, VM.Config.HWType, Sys.Audit, VM.Console, Datastore.Allocate, VM.Snapshot.Rollback, VM.PowerMgmt, VM.Migrate, VM.Config.Memory, VM.Config.CDROM, Sys.Console, VM.Snapshot, Pool.Allocate, VM.Backup, Datastore.Audit, Sys.PowerMgmt, VM.Config.Options, Sys.Syslog, VM.Config.Disk, VM.Clone, VM.Monitor, SDN.Allocate`

We also applied the right uterra is a member of TerraformGroup : 
```
pveum aclmod / -user uterra@pve -role PVETerraformGroup
pveum aclmod / -group TerraformGroup -role PVETerraformGroup
```

We are using a Proxmox 6.1-3 (I haven't specified it)

**Comment by danitso-dp** [comment]
I'll take a look at it and get back to you.

**Comment by Crazyscorpio88** [comment]
@danitso-dp if you are aware of others rights needed for Terraform, just tell me. I'll try to apply them.

**Comment by danitso-dp** [comment]
Your permissions appear to be fine. This is a limitation enforced in PVE for at least the `arch` and `args` API parameters.

Currently, the provider only supports changes to `arch` but I'll make sure to add the same exception in case `args` is introduced at some point.

**Comment by Crazyscorpio88** [comment]
Ok, perfect, I'll be waiting for your Release.

**Comment by danitso-dp** [comment]
@Crazyscorpio88 the first go at this change is available in #11. I haven't tested it yet but I'll do that later. You can also test it yourself, if you're able to build the provider.

**Comment by Wombelix** [comment]
@danitso-dp i had the same issue as @Crazyscorpio88 your Pull Request #11 worked for me.

**Comment by danitso-dp** [comment]
@Wombelix thanks for testing it. I've just merged it.

@Crazyscorpio88 are you able to get it working as well? I can do a pre-release of v0.4.0, if you need a binary release for testing purposes.

**Comment by Crazyscorpio88** [comment]
I cannot test it at the moment, the platform is shutdown during week-ends. But as soon as I access it I will test your update.

Thanks for the PR.

**Comment by danitso-dp** [comment]
@Crazyscorpio88 sounds great. I'll let this issue remain open until you get a chance to test it out :)

**Comment by Crazyscorpio88** [comment]
@danitso-dp It works perfectly :)
Thanks for the commit.

**Comment by danitso-dp** [comment]
@Crazyscorpio88 Great to hear. I'll close this issue then. Don't hesitate to submit new bug reports, if you run into other issues.

**Comment by Shackelford-Arden** [comment]
@danitso-dp Out of curiosity, is there an ETA on a release for this? I've run into this issue was well, but when I build off of master it seems that there are a number of things that have changed that do not yet have documentation (ie; `proxmox_virtual_environment_vm` doesn't appear to be the same).
