### ISSUE TITLE
[FEATURE] Create multiple VM with count parameter

### ISSUE THREAD

**Issue by itek09** [danitso/terraform-provider-proxmox#14]
Hello!

When you try to create multiple VM with count parameter, all the VMs try to lock the same ID in proxmox, so only the first one is successfully created.

I don't know about the Proxmox API, but possible solutions:
-Ask about the last id in each count look (I suppose you are asking the next available id using the API).
-Use a random id since the last available or maybe increase it with count.

Thank you for your time

**Comment by alexbgreat** [comment]
> count = 4
> vm_id     = 4321 + count.index

works for me.

**Comment by itek09** [comment]
> > count = 4
> > vm_id     = 4321 + count.index
> 
> works for me.

Sorry, the issue happens without the vm_id parameter (to allocate the next free id)

**Comment by danitso-dp** [comment]
Hi @itek09 

The initial fix is available in PR #16

**Comment by itek09** [comment]
Thank you so much.

Again, amazing work ;)
