### ISSUE TITLE
[BUG] Disk image fails to import correctly when using directory storage

### ISSUE THREAD

**Issue by alexbgreat** [danitso/terraform-provider-proxmox#15]
I'm unable to successfully deploy the ubuntu-cloud demo when using a directory-based storage. I'm using a local datastore called bulk. I'm assuming this would also affect NFS stores.

> transferred: 8589934592 bytes remaining: 0 bytes total: 8589934592 bytes progression: 100.00 %
> Successfully imported disk as 'unused0:bulk:4321/vm-4321-disk-0.qcow2'
> unable to parse directory volume name 'vm-4321-disk-0'

storage.cfg : 
>dir: bulk
>       path /mnt/pve/bulk
>       content iso,backup,snippets,rootdir,vztmpl,images
>       is_mountpoint 1
>       nodes marlene

Relevant code - terraform-provider-proxmox/proxmoxtf/resource_virtual_environment_vm.go 1628
> fmt.Sprintf(\`qm set %d -scsi%d %s:vm-%d-disk-%d%s\`, vmID, i, datastoreID, vmID, diskCount+importedDiskCount, diskOptions),

Output of this code 
> \# qm set 4321 -scsi0 bulk:vm-4321-disk-0.qcow2
> unable to parse directory volume name 'vm-4321-disk-0.qcow2'

What I'm guessing the code really should be (when using directory storage)
> fmt.Sprintf(\`qm set %d -scsi%d %s:%d/vm-%d-disk-%d%s\`, vmID, i, datastoreID, vmID, vmID, diskCount+importedDiskCount, diskOptions),

How the code should run (when using directory storage)
> \# qm set 4321 -scsi0 bulk:4321/vm-4321-disk-0.qcow2
> update VM 4321: -scsi0 bulk:4321/vm-4321-disk-0.qcow2

**Comment by danitso-dp** [comment]
Hi @alexbgreat 

I'll take a look at this issue and get back to you with a fix.

**Comment by danitso-dp** [comment]
Hi @alexbgreat 

The initial fix for this can be found in #17

**Comment by danitso-dp** [comment]
Just to clarify: I haven't had a chance to test it yet but I'll get around to doing that soon :)

In case you have the time, do go ahead and give it a try.

**Comment by alexbgreat** [comment]
Very close. The only thing missing is you need to keep track of the file extension.

**Comment by alexbgreat** [comment]
> \# disk_id=bulk:4324/vm-4324-disk-0
> \# qm set "4324" "-scsi0" "bulk:4324/vm-4324-disk-0"
> unable to parse volume filename 'vm-4324-disk-0'
> \# qm set "4324" "-scsi0" "bulk:4324/vm-4324-disk-0.qcow2"
update VM 4324: -scsi0 bulk:4324/vm-4324-disk-0.qcow2

**Comment by danitso-dp** [comment]
Ah yes, forgot about that part. I've pushed a commit which should fix it.

**Comment by danitso-dp** [comment]
I'm closing this now that #17 is merged. Don't hesitate to open a new issue in case you run into another problem.
