### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hoshsadiq** [danitso/terraform-provider-proxmox#3]
**Describe the bug**
Non-https URLs not accepted

**To Reproduce**

```
provider "proxmox" {
  version = "0.3.0"

  virtual_environment {
    endpoint = "http://a.b.c.d:8006"
    username = "someuser"
    password = "somepass"
  }
}
```

**Expected behavior**
Plan/apply etc should run

**Actual behaviour**
```
Error: You must specify a secure endpoint for the Proxmox Virtual Environment API (valid: https://host:port/)

  on main.tf line 7, in provider "proxmox":
   7: provider "proxmox" {
```

**Additional context**
Offending error is at

```
	if url.Scheme != "https" {
		return nil, errors.New("You must specify a secure endpoint for the Proxmox Virtual Environment API (valid: https://host:port/)")
	}
```

Is there a reason this was developed to require `https`? I totally understand `https` is the better solution (obv) but right now I'm trying to do the initial setup, which of course requires http as https hasn't been setup yet. I'd be happy to raise an PR to allow http, but I wanted to understand the reasoning behind this first.

**Comment by danitso-dp** [comment]
Hi @hoshsadiq 

The testing of the provider is currently being performed against a clean installation of Proxmox VE 6.1, which comes with HTTPS and a self-signed certificate. This is why the `insecure` argument was added so you can do HTTPS with a clean installation.

I've just tried to access a clean installation of Proxmox VE 6.1 using HTTP, which results in an empty response. Are you sure your setup will accept HTTP?

**Comment by hoshsadiq** [comment]
Aah! You are absolutely right. For whatever reason I did not notice this. That's what I get for doing this late in the night. Thanks
