### ISSUE TITLE
[BUG] Output VM Resource IPs only 127.0.0.1

### ISSUE THREAD

**Issue by ikeingtonbear** [danitso/terraform-provider-proxmox#33]
**Describe the bug**
I have a cloud-init enabled template which I use as base VM. In my terraform I use the initialization block to assign an IPv4 address to my newly created VM. In my terraform I also have an output to write out a the IP addresses to the terminal for me newly created VM. My returned output on build is:
```
Outputs:

test_ip_addr = [
  [
    "127.0.0.1",
  ],
  [],
]
```
This output does not include the assigned IP address of the newly created VM. 

**To Reproduce**
1. Create a cloud-init enabled template VM
2. Using terraform create a clone of the template, and assign it an IPv4 address in the initialization block
```
initialization {
        ip_config {
            ipv4 {
                address = "10.0.1.100/24"
                gateway = "10.0.0.1"
            }
        }
    }
```
3. Include an output block in terraform to print the newly created VM's ip addresses
```
output "test_ip_addr" {
    value = proxmox_virtual_environment_vm.test_vm.ipv4_addresses
}
```
4. Run `terraform apply`

**Expected behavior**
The expected output of the Ip addresses should look like
```
Outputs:

test_ip_addr = [
  [
    "127.0.0.1",
  ],
  [
    "10.0.1.100",
  ],
]
```

**Screenshots**
Text output included

**Additional context**
The proper output can be achieved by running a `terraform refresh`

**Comment by ikeingtonbear** [comment]
Adding clarification: qemu-agent is installed, and the agent enabled block is set to true.

**Comment by HarishHary** [comment]
I am facing the same issue with a VM created from a template.
That template was itself created using `packer`. qemu-agent is installed.

```
resource "proxmox_virtual_environment_vm" "linuxstation" {
  name = var.linuxstation["name"]
  node_name = var.linuxstation["target_node"]

  clone {
    vm_id = 2000 # Ubuntu1604-template
  }
  operating_system {
    type = "l26"
  }
  cpu {
    cores = var.linuxstation["cores"]
    units = var.linuxstation["memory"]
  }
  disk {
    size = var.linuxstation["disk_size"]
    datastore_id = "local-lvm"
  }
  agent {
    enabled = true
  }
  network_device {
    model = "e1000"
    bridge = var.proxmox_config["nat_network"]
  }
}
```

**Comment by danitso-dp** [comment]
Can I get you to go into the Proxmox Web UI and check, if your VMs report any IP addresses?

**Comment by ikeingtonbear** [comment]
<img width="601" alt="Screen Shot 2020-06-19 at 19 32 38" src="https://user-images.githubusercontent.com/13791199/85185821-ae0fd100-b263-11ea-86fe-4c13c656b2cb.png">

Attached is the output from Proxmox for the VM i referenced earlier.

**Comment by HarishHary** [comment]
Hello,

I think the issue is related to timing. Looks like the qemu-agent is not yet ready to be read.
As of right now, all my linux machines have ip addresses provided by DHCP and I think we must wait a bit before getting the end ip.

**Comment by danitso-dp** [comment]
@HarishHary it does indeed sound like a timing issue. However, does any of you see Terraform waiting for 15 minutes before continuing or does it continue almost right after the VM is created?

**Comment by HarishHary** [comment]
It does continue right after the VM is created. Another fact is, even if I have a `provider` in my case it is a `local-exec` provider. It does not resolve the IP address. So either it does not get the address at the end of the ressources graph: https://www.terraform.io/docs/internals/graph.html#walking-the-graph, or something else is going on. I will try to check the code first. Do you know where I can look up first ?

**Comment by danitso-dp** [comment]
@HarishHary I'm trying to investigate whether the QEMU agent is in fact returning IP adresses but for the local interface only. Can you try to run apply with TF_LOG set to DEBUG and look for lines containing `network-get-interfaces`? This way we can see, if the calls are being made and whether they fail or not.

**Comment by HarishHary** [comment]
Should I try with your patch ? Or the provider from master ? I will be able to give you an answer on monday if that's okay for you.

**Comment by HarishHary** [comment]
You will find attached the logs that you asked for.
[log_tf.txt](https://github.com/danitso/terraform-provider-proxmox/files/4844449/log_tf.txt)

**Comment by HarishHary** [comment]
Just tested your current fix, still not it. I added a more verbose debug to see what proxmox returned when you try to get the network interfaces:

```

2020-06-29T10:19:59.119+0200 [DEBUG] plugin.terraform-provider-proxmox: 2020/06/29 10:19:59 [DEBUG] Performing HTTP GET request (path: nodes/proxmox/qemu/102/agent/network-get-interfaces)
2020-06-29T10:20:02.204+0200 [DEBUG] plugin.terraform-provider-proxmox: 2020/06/29 10:20:02 [DEBUG] WARNING: Received an HTTP 500 response - Reason: QEMU guest agent is not running
proxmox_virtual_environment_vm.linuxstation: Still creating... [1m10s elapsed]
2020-06-29T10:20:04.204+0200 [DEBUG] plugin.terraform-provider-proxmox: 2020/06/29 10:20:04 [DEBUG] Performing HTTP GET request (path: nodes/proxmox/qemu/102/agent/network-get-interfaces)
2020-06-29T10:20:05.292+0200 [DEBUG] plugin.terraform-provider-proxmox: 2020/06/29 10:20:05 &[{MACAddress:00:00:00:00:00:00 Name:lo Statistics:<nil> IPAddresses:0xc00078a540} {MACAddress:6e:c4:11:d0:53:10 Name:eth0 Statistics:<nil> IPAddresses:<nil>}]
2020/06/29 10:20:05 [WARN] Provider "registry.terraform.io/-/proxmox" produced an unexpected new value for proxmox_virtual_environment_vm.linuxstation, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .disk[0].file_id: was null, but now cty.StringVal("")
      - .clone[0].datastore_id: was null, but now cty.StringVal("")
      - .clone[0].node_name: was null, but now cty.StringVal("")
      - .network_device[0].mac_address: was null, but now cty.StringVal("6E:C4:11:D0:53:10")
proxmox_virtual_environment_vm.linuxstation: Creation complete after 1m11s [id=102]
2020-06-29T10:20:05.309+0200 [DEBUG] plugin: plugin process exited: path=/home/hary/.terraform.d/plugins/terraform-provider-proxmox pid=24916
2020-06-29T10:20:05.309+0200 [DEBUG] plugin: plugin exited
```
As you can see it returns 2 interfaces but the second one does not have an address yet.

**Comment by HarishHary** [comment]
Hello,

I just tested your solution. It is working after I added some missing condition. You might need to test it more carefully than me.

```
for index, nic := range *data.Result {
	if (*data.Result)[index].Name == "lo" {
		continue
	}
	if nic.IPAddresses == nil || (nic.IPAddresses != nil && len(*nic.IPAddresses) == 0) {
		missingIP = true
		break
	}
}
```

**Comment by danitso-dp** [comment]
@HarishHary the PR was simply to test, if the issue occurred because lo showed up with IP addresses before any other interfaces were reported by the agent. However, we seem to be on the right track with your continued testing so I'll try to modify the code with your suggestions so we can give it another go.

**Comment by HarishHary** [comment]
Hello @danitso-dp, any progress on my suggestion ?
