### ISSUE TITLE
[BUG] Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by dmeulen** [danitso/terraform-provider-proxmox#4]
Thank you for creating this provider. 
Most of the time it just works, but from time to time I get this error and it can only be fixed by cleaning the states and start all over.

**Versions used**

```
terraform 0.12.23
terraform-provider-proxmox 0.3.0-custom
proxmox 6.1-3
```

**Debug log**
[debug.log](https://gist.github.com/dmeulen/6ba5ea2427a4e24389a70a32027c44cc)

**API result**
For what it is worth, this is the API result I get from proxmox..
[API result](https://gist.github.com/dmeulen/a29d263f048e7958b2735fba347de57a)

**Comment by danitso-dp** [comment]
Hi @dmeulen 

I've pushed an initial fix which checks whether IP addresses are actually detected by the QEMU agent. This will result in an empty list instead of a crash, if they're not detected. However, this might require some additional logic in case this is a timing issue and the agent in fact does know about the IP addresses.

Can you perhaps try to trigger this issue again without using the new code? Once it crashes, try to open the Web UI and inspect the QEMU agent data (the list of IP addresses on the overview page). In case this list is not empty when you experience the crash, we'll know for sure that this is a timing issue.

**Comment by danitso-dp** [comment]
I've pushed a few more commits, which makes the provider wait for IP addresses to become available and also adds a new `timeout` argument for the `agent` block, which controls the maximum amount of time to wait for this data to become available.

**Comment by dmeulen** [comment]
I just ran into the issue again during a plan (old code). I checked the QEMU agent data and the lists are not empty.

**Comment by danitso-dp** [comment]
Basically, the provider queries the following endpoint for the information:

https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/network-get-interfaces

I haven't experienced any issues myself using the `example` project. However, can you provide some additional information about your virtual machine? Then I'll try to replicate the configuration as much as possible and see if I can narrow down the issue.

**Comment by danitso-dp** [comment]
Using bash or a compatible shell, can you try to do the following:

1. Create a new access ticket in PVE: `curl -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'username=root@pam' --data-urlencode 'password=your-password-here' -k https://the-api-hostname-or-address-here:8006/api2/json/access/ticket`
2. Find the `"ticket": "PVE:root@pam:..."` part of the response and copy the long `PVE:root@pam:...` value
3. Query the QEMU agent: `curl --cookie 'PVEAuthCookie=PVE:root@pam:...' -k https://the-api-hostname-or-address-here:8006/api2/json/nodes/the-node-name-here/qemu/the-virtual-machine-id-aka-vmid-here/agent/network-get-interfaces`
4. Post the JSON response in this thread, which should be something similar to this:

```json
{
   "data":{
      "result":[
         {
            "name":"lo",
            "hardware-address":"00:00:00:00:00:00",
            "statistics":{
               "rx-errs":0,
               "tx-packets":130,
               "tx-dropped":0,
               "rx-bytes":11402,
               "rx-dropped":0,
               "tx-bytes":11402,
               "tx-errs":0,
               "rx-packets":130
            },
            "ip-addresses":[
               {
                  "prefix":8,
                  "ip-address":"127.0.0.1",
                  "ip-address-type":"ipv4"
               },
               {
                  "prefix":128,
                  "ip-address-type":"ipv6",
                  "ip-address":"::1"
               }
            ]
         },
         {
            "ip-addresses":[
               {
                  "prefix":24,
                  "ip-address-type":"ipv4",
                  "ip-address":"10.0.0.13"
               },
               {
                  "ip-address-type":"ipv6",
                  "ip-address":"fe80::cc64:fcff:fe25:ccfa",
                  "prefix":64
               }
            ],
            "statistics":{
               "tx-dropped":0,
               "rx-bytes":37879364,
               "rx-errs":0,
               "tx-packets":3298,
               "tx-errs":0,
               "rx-packets":80541,
               "rx-dropped":34629,
               "tx-bytes":287270
            },
            "hardware-address":"ad:64:cc:25:a2:fe",
            "name":"eth0"
         }
      ]
   }
}
```

**Comment by danitso-dp** [comment]
I've pushed another commit which outputs more debugging information during HTTP requests. I suspect that the response might not be able to be decoded for some reason, which the new debug output should reveal. Please try to request the raw output from the endpoint using the above steps but also try to run with `TF_LOG=DEBUG` with the latest code until you experience the issue again, so we can hopefully do a permanent fix for this.

**Comment by dmeulen** [comment]
JSON response:
```
{
    "data": {
        "result": [
            {
                "ip-addresses": [
                    {
                        "ip-address-type": "ipv4",
                        "ip-address": "127.0.0.1",
                        "prefix": 8
                    }
                ],
                "statistics": {
                    "tx-bytes": 46697886,
                    "rx-dropped": 0,
                    "tx-errs": 0,
                    "tx-packets": 213452,
                    "tx-dropped": 0,
                    "rx-errs": 0,
                    "rx-bytes": 46697886,
                    "rx-packets": 213452
                },
                "name": "lo",
                "hardware-address": "00:00:00:00:00:00"
            },
            {
                "statistics": {
                    "rx-bytes": 79225798,
                    "rx-errs": 0,
                    "tx-dropped": 0,
                    "rx-packets": 481216,
                    "rx-dropped": 85,
                    "tx-errs": 0,
                    "tx-bytes": 47858288,
                    "tx-packets": 156803
                },
                "name": "eth0",
                "hardware-address": "d6:d0:f6:62:04:78",
                "ip-addresses": [
                    {
                        "ip-address": "192.168.1.144",
                        "ip-address-type": "ipv4",
                        "prefix": 24
                    },
                    {
                        "prefix": 64,
                        "ip-address-type": "ipv6",
                        "ip-address": "fe80::d4d0:f6ff:fe62:478"
                    }
                ]
            },
            {
                "ip-addresses": [
                    {
                        "ip-address": "172.17.0.1",
                        "ip-address-type": "ipv4",
                        "prefix": 16
                    }
                ],
                "hardware-address": "02:42:27:7b:74:a0",
                "name": "docker0",
                "statistics": {
                    "tx-packets": 3781,
                    "tx-bytes": 447762,
                    "rx-dropped": 0,
                    "tx-errs": 0,
                    "rx-packets": 3781,
                    "rx-errs": 0,
                    "tx-dropped": 0,
                    "rx-bytes": 252364
                }
            },
            {
                "name": "veth5a4cbc8",
                "hardware-address": "32:4d:ea:04:0a:0c"
            }
        ]
    }
}
```
Since the last code it doesn't crash anymore, but it does seem to timeout, see [debug.log](https://gist.github.com/dmeulen/3fff4a8c2e0db5f9f76e584629ba7481)

**Comment by danitso-dp** [comment]
Ah, yes. There we go.
```
            {
                "name": "veth5a4cbc8",
                "hardware-address": "32:4d:ea:04:0a:0c"
            }
```
There are no IP addresses for that one. Right now the code expects some to be returned.

I'll look at a permanent fix for this.

**Comment by dmeulen** [comment]
Ah! The docker interfaces!

**Comment by danitso-dp** [comment]
I've pushed a new commit which also makes the `statistics` optional in the response.

**Comment by dmeulen** [comment]
Timeout is gone and all seems well with the latest build! Thanks! Keep up the good work!

**Comment by danitso-dp** [comment]
Great to hear :)

I'm marking this as resolved.
