### ISSUE TITLE
[BUG] Creating a VM resource always fails if `pool_id` (an argument marked optional) is not supplied

### ISSUE THREAD

**Issue by fabacab** [danitso/terraform-provider-proxmox#41]
This was previously reported in #2 but that bug report contained numerous distinct issues and was thus a bit confusing to track. I ran into this same bug today and figured I'd help make sure it wasn't lost in the shuffle of old, closed issue reports. So, the existing issue as originally reported:

> I also have to set `pool_id` in the template or it fails with
>
> ```
> Error: Received an HTTP 400 response - Reason: Parameter verification failed. (pool: invalid format - pool name '' contains invalid characters)
> ```
>
> I am not using pools.

This is exactly the issue I'm having. See below.

## To Reproduce

1. Set up a single-node Proxmox VE cluster (6.2-11 is what I'm using, the current stable release).
1. Create a simple, test VM with the following Terraform version 0.13.2 configuration (`provider` block is omitted for brevity):
    ```hcl
    data "proxmox_virtual_environment_nodes" "pve_nodes" {}
    
    resource "proxmox_virtual_environment_file" "ubuntu_cloud_image" {
      content_type = "iso"
      datastore_id = "local"
      node_name    = data.proxmox_virtual_environment_nodes.pve_nodes.names[0]
    
      source_file {
        path = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
      }
    }
    
    resource "proxmox_virtual_environment_vm" "testvm" {
      node_name  = data.proxmox_virtual_environment_nodes.pve_nodes.names[0]
    
      # The documentation describes the `pool_id` as optional, but if it's commented out
      # like it is here, creating the VM resource will always fail.
      #pool_id   = proxmox_virtual_environment_pool.test_pool.id
    
      disk {
        datastore_id = "local-lvm"
        file_id      = proxmox_virtual_environment_file.ubuntu_cloud_image.id
      }
    }
    
    # The documentation describes a `pool_id` argument to the `proxmox_virtual_environment_vm`
    # resource as optional, but without a pool such as shown here, creating the VM resource
    # will always fail.
    #resource "proxmox_virtual_environment_pool" "test_pool" {
    #  comment = "Pools should be optional, but currently are not!"
    #  pool_id = "test_pool"
    #}
    ```
1. Apply the Terraform configuration with `terraform apply` and observe the error quoted above.

## Expected behavior

One of two things should be true:

1. The documentation correctly describes the `pool_id` value as a required argument, because it currently is. Or, preferably,
1. the provider does not require setting a `pool_id` argument for a `proxmox_virtual_environment_vm` resource when it is being created.

In order to work around the issue, we must add `proxmox_virtual_environment_vm` resources to `proxmox_virtual_environment_pool` resources by the latter resource's `id` values at create time. To see this work, uncomment the commented code in the above sample configuration.

**Comment by danitso-dp** [comment]
@fabacab do you still experience this issue with the latest version?

**Comment by fabacab** [comment]
> @fabacab do you still experience this issue with the latest version?

No, this is fixed now. Thanks.
