### ISSUE TITLE
[BUG] Changing static IP of container does not work

### ISSUE THREAD

**Issue by rrelmy** [danitso/terraform-provider-proxmox#45]
**Describe the bug**
Changing the ip address of a container does not change it.

**To Reproduce**
1. create a container with a static ip
``` tf
resource "proxmox_virtual_environment_container" "somecontainer" {
// ...
  initialization {
    ip_config {
      ipv4 {
        address = "10.44.0.3/32"
        gateway = "10.44.0.1"
      }
    }
// ...
```
2. change the ip
3. apply
4. apply again and see that the ip did not change

**Expected behavior**
Changing ip should work

**Comment by danitso-dp** [comment]
@rrelmy I can confirm that this issue exists. I'll look into a fix for it.

**Comment by danitso-dp** [comment]
@rrelmy check out #73 to see, if it fixes your issue.
