### ISSUE TITLE
[BUG] (potentially?) proxmox_virtual_environment_file uses local IP for upload instead of the connection details in the provider.

### ISSUE THREAD

**Issue by shutupflanders** [danitso/terraform-provider-proxmox#65]
**Describe the bug**
When trying to upload a file to a node, instead of using the endpoint in the provider it retrieves and uses the node's internal IP address.
I'm accessing a remote cluster therefore the local IP doesn't resolve.

I hope I'm wrong and I've just missed something though.

**To Reproduce**
```
resource "proxmox_virtual_environment_file" "test_file" {
  datastore_id = "local"
  node_name    = "cluster-node-01"

  content_type = "snippets"
  source_raw  {
    data = "test"
    file_name = "test.txt"
  }
}
```
**Expected behavior**
It should upload the file to the destination (in this case the endpoint set in the provider config) or allow us to specify connection information.

**Screenshots**
```
Error: dial tcp 172.27.27.11:22: connect: connection timed out

  on main.tf line 296, in resource "proxmox_virtual_environment_file" "test_file":
 296: resource "proxmox_virtual_environment_file" "test_file" {
```

**Additional context**

**Comment by blz-ea** [comment]
Hey @shutupflanders,
Due to Proxmox API limitations it is only allowed to upload "iso" or "vztmpl" types.
Other types uploaded over SFTP. 
Hopefully future Proxmox releases will have support for "snippets"
