### ISSUE TITLE
[BUG] resourceVirtualEnvironmentVMCreateCustom has a typo and resourceVirtualEnvironmentVMCreateCustomDisks only handles scsi disk imports regardless of the resource definition

### ISSUE THREAD

**Issue by mleone87** [danitso/terraform-provider-proxmox#67]
**Describe the bug**
There is a typo in the code and an hard coded value in the custom command sent to proxmox

**To Reproduce**
1. Create a resource with virtio disk and it will be created with a scsi interface

**Expected behavior**
Interface should be coherent with the resource definition

**Comment by danitso-dp** [comment]
@mleone87 can we close this issue now that #61 is merged?
