### ISSUE TITLE
[FEATURE] boot order and netboot

### ISSUE THREAD

**Issue by yuqo2450** [danitso/terraform-provider-proxmox#81]
It would be great if it was possible to set a boot order in terrform for vms and enable and disable boot options.
We are installing our systems with pxe (foreman). Therefore we need to boot vms on first boot via network.

Would be great if it was possible to add this feature in future versions.

**Comment by danitso-dp** [comment]
I've added this to the v0.5.0 milestone.

**Comment by yuqo2450** [comment]
Closing this issue because repository is not actively maintained.
