### ISSUE TITLE
[BUG] Parameter verification failed - disk - interface 

### ISSUE THREAD

**Issue by Shackelford-Arden** [danitso/terraform-provider-proxmox#85]
**Describe the bug**

Supplying what appears to be valid data from the documentation of either "scsi","sata" or "virtio", we received a 400 error from Proxmox. Specifically, the following message:

`
Received an HTTP 400 response - Reason: Parameter verification failed. (scsi: property is not defined in schema and the schema does not allow additional properties)
`

**To Reproduce**

Proxmox Version: 6.3-2

Attempt to use the following Terraform files (sanitized):

providers.tf
```terraform
terraform {
  required_providers {
    proxmox = {
      source = "danitso/proxmox"
      version = "0.4.4"
    }
  }
}

provider "proxmox" {
  virtual_environment {
    endpoint = "https://proxmox_host.local:8006"
    username = "tf_user@pve"
    password = "tf is awesome"
    insecure = false
  }
}
```

main.tf
```terraform
resource "proxmox_virtual_environment_vm" "vm" {
  count        = 1
  name         = "vm-${count.index}"
  description  = "Playground vm"
  node_name    = "proxmox_host"

  agent {
    enabled = true
  }
  bios = "ovmf"
  cpu {
    cores   = 4
    sockets = 1
    type    = "host"
  }

  memory {
    dedicated = 2048
  }

  disk {
    datastore_id = "vmdisks"
    file_format  = "qcow2"
    interface    = "scsi"
    size         = 15
  }

  initialization {
    datastore_id = "local-lvm"
    user_account {
      username = "fancyuser"
      password = "password123"
      keys     = [data.tls_public_key.internal_ssh_key.public_key_pem]

    }
  }

  operating_system {
    type = "l26"
  }

  started = true
  vm_id   = 1100

}

data "tls_public_key" "internal_ssh_key" {
  private_key_pem = file("~/.ssh/id_rsa")
}
```

**Expected behavior**

A successful apply :)

**Comment by v12** [comment]
@Shackelford-Arden `interface` property is a combination of bus and device ID values. In your example, the value should be an exact interface, so in your example it would be `scsi0`

**Comment by Shackelford-Arden** [comment]
I'll give that a go and report back :) Thanks!

**Comment by Shackelford-Arden** [comment]
Appears to be working :P I seem to have misread you're docs. Thanks!
