### ISSUE TITLE
Question about create vm from iso

### ISSUE THREAD

**Issue by jehutyy** [danitso/terraform-provider-proxmox#9]
Hi, 
I'm trying to figure out how to specify an iso from an already existing pool. 
I have uploaded iso to my proxmox cluster and I would like to use them to provision a vm. 

From documentation, I can't figure out how to do that, I thought about a data source that would provide a access to available iso from cluster but I can't find anything like that.

**Comment by danitso-dp** [comment]
Hi @jehutyy 

There's currently not a data source available for crawling the list of files in a datastore. However, the format for an ISO file is the following:

```
<datastore-name>:iso/<filename>
```
i.e.
```
local:iso/bionic-server-cloudimg-amd64.img
```

You should be able to use this as the `file_id`.

In case you want to avoid specifying it manually, you can also upload the ISO file using Terraform. You can see how this is done here:

https://github.com/danitso/terraform-provider-proxmox/blob/master/example/resource_virtual_environment_file.tf#L38-L46

and how it's used for creating a VM template here:

https://github.com/danitso/terraform-provider-proxmox/blob/master/example/resource_virtual_environment_vm.tf#L8-L11

**Comment by jehutyy** [comment]
Great, thank you, that should do the tricks, I try that and get back to you if anything went wrong.

**Comment by danitso-dp** [comment]
You're very welcome :)

I'm closing this issue but don't hesitate to create a new one, if you experience other issues.
